test/index.js
Now that Crowdin is using the new flat key-value YML structure, all is well and the keys line up.
🔑 🔑 🔑 🔑 🔑 🔑
=> test congruency of API descriptions

index.js, lib/apis.js, lib/get-slugs.js, lib/locales.js, lib/pretranslate.js, readme.md, test/index.js
This PR adds support for fetching translated API object using the `name` or the `slug` of the API.
```js
i18n.api.get('BrowserWindow')
// or 
i18n.api.get('browser-window')
```
=> Get API by slug

package.json
For some reason npm freaks out about github:foo/bar modules that have script hooks.
We are not currently publishing this module to npm, so it's safe to remove this check for now. Also set `private` to `true` in the package.json to prevent publishes.
```
-----> Building dependencies
Installing node modules (package.json + package-lock)
> electron-i18n@1.0.0 prepack /app/.npm/_cacache/tmp/git-clone-aebac26d
> check-for-leaks
sh: 1: check-for-leaks: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electron-i18n@1.0.0 prepack: `check-for-leaks`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the electron-i18n@1.0.0 prepack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm …
```
=> disable prepack check

code_of_conduct.md, contributing.md, crowdin.md, license, readme.md
This PR: 
- lightens up the README
- moves Crowdin info to its own doc
- adds a [Contributor Covenant](contributor-covenant.org) Code of Conduct
- adds an MIT license file
- documents the build process
📝 ⚖️ 💡 
cc @alebourne @bernars
=> add license, CoC, and contributing doc

script/build.js, test/index.js
This is an optimization so the website won't have to sort the docs for `/docs` index page.
=> sort docs by slug per locale

script/build.js, test/index.js
Ensure that docs always have titles by plucking `h2` text if `h1` is empty.
Change:
`file.title = $('h1').text() !== '' ? $('h1').text() : $('h2').text() `
/cc @zeke
=> ensure doc always has title

script/build.js, test/index.js
This updates the title tests to make sure we're not checking empty collections. This is a subtle gotcha of using `some` and `every` in tests.
Note how this returns true even though it's kind of a logical fallacy or something:
```
$ node          
> [].every(thing => thing === 'hello')
true
```
=> fix: make titles test more robust

lib/language-table.js, readme.md
This should make it more obvious where translators should go when they land on this repo's readme.
cc @codebytere
=> add language list to readme

package-lock.json, package.json
Trying a major bump of `semantic-release` to see if we can recover from the issues outlined in https://github.com/semantic-release/semantic-release/issues/482
=> fix: use new major version of semantic-release

package.json, script/build.js, test/index.js
Markdown docs are written for consumption in GitHub, so they have HREFS like `../glossary.md#main-process`. This PR updates all relative links in the docs to match the URL of that content on the website, e.g. `/docs/glossary#main-process`
=> fix relative links in docs

content/en-US/docs/api/browser-view.md, content/en-US/docs/api/browser-window-proxy.md, content/en-US/docs/api/browser-window.md, content/en-US/docs/api/client-request.md, content/en-US/docs/api/dialog.md, content/en-US/docs/api/file-object.md, content/en-US/docs/api/incoming-message.md, content/en-US/docs/api/menu-item.md, content/en-US/docs/api/menu.md, content/en-US/docs/api/notification.md, content/en-US/docs/api/touch-bar-scrubber.md, content/en-US/docs/api/touch-bar.md, content/en-US/docs/api/web-contents.md, content/en-US/docs/development/build-instructions-linux.md, content/en-US/docs/development/releasing.md, content/en-US/docs/faq.md, content/en-US/docs/glossary.md, content/en-US/docs/tutorial/installation.md, content/en-US/docs/tutorial/windows-store-guide.md, content/en-US/electron-api.json, content/en-US/website/locale.yml
This bumps the source content from Electron 1.7.5 to 1.7.9.
For reference, the last PR that updated source content was #71 
This update was run using the refactored collector in #129
=> update source content to 1.7.9

.github/config.yml
If just:
```
[contributing guidelines](contributing.md)
```
Will be rendered this URL: https://github.com/electron/electron-i18n/pull/contributing.md
I do not know if this happened before or not. So I edited it to the right URL.
Can check at that comment of the `bot`: https://github.com/electron/electron-i18n/pull/136#issuecomment-342536457
=> Fix incorrect URL (welcome bot comment)

contributing.md, script/collect.js
=> electron.atom.io → electronjs.org

readme.md
This updates the usage docs in the README to describe the `i18n.website` object.
=> add missing documentation for i18n.website object

package.json
This PR takes `npm run stats` out of the `pretest` script, so `npm test` will run without requiring a `.env` file or any secrets in the env.
Fixes #165
=> enable tests to run without env secrets

script/stats.js
https://travis-ci.org/electron/electron-i18n/builds/310025376 is failing because dot-env is called needlessly by the stats script. This should fix that.
=> do not load env in stats script

script/stats.js
Should be merged **after** electron/electronjs.org#939
=> Switch to using new language-stats route `/crowdin/status`

crowdin.yml
This is an attempt to change the wording of commit messages that come from Crowdin via @glotbot, so `semantic-release` will know to automatically create new releases when Crowdin PRs are merged. This `commit_message` property appears to be [undocumented](https://support.crowdin.com/configuration-file/) so I'm not sure what to expect..
Fixes #188
=> customize crowdin commit message

script/build-module.js, test/index.js
Fixes https://github.com/electron/electronjs.org/issues/964 where the inner html of each doc is a complete html document itself (i.e. contains opening and closing tags like `<html>`, `<body>`, etc).
Related: https://github.com/cheeriojs/cheerio/issues/1031#issuecomment-306329834
=> retain only html within the <body> tag for each doc

package.json
We had a script that had `node` prefix added unnecessarily. This fixes it. @vanessayuenn
=> bash, not node

content/en-US/docs/tutorial/electron-versioning.md
- backport
- stabilization branch
- and some typo.
=> fix typo for electron-versioning.md

content/en-US/docs/tutorial/electron-versioning.md
Reverts electron/electron-i18n#243
Sorry for the confusion @dakeshi and @ckerr but these changes should actually have been made on the https://github.com/electron/electron repository, which is the source from which all the docs are collected. We have a [commenting bot](https://github.com/electron/electron-i18n/pull/243#issuecomment-365457437) that tries to make it clear, but it is sometimes overlooked. Please open a pull request over on electron/electron.
Thanks!
=> Revert "fix typo for electron-versioning.md"

contributing.md
Adds some quick pointers for new translators. Also gives us a URL we can send to drive-by people asking for proofreader status.
=> add some translator guidelines

readme.md, test/index.js
This PR adds an extra test so we can always rely on every doc having a `crowdinFileId` property.
cc @pierreneter @vanessayuenn
=> Assert crowdin file ids

readme.md
Happy to suggest Hebrew to the official readme.md of Electron.
Thats the only change.
=> docs: add Hebrew to README

test/glossary.js
Something is wrong with the construction of the Crowdin glossary. This PR disables those tests to unblock getting updated Electron version data on the site.
=> fix: disable crowdin glossary tests

readme.md
greenkeeper badge is empty, we now using dependabot.
replace greenkeeper badge to dependabot badge.
[![Dependabot badge](https://img.shields.io/badge/Dependabot-enabled-blue.svg)](https://dependabot.com/)
=> chore: replace greenkeeper badge to dependabot badge

lib/remark-fiddle-urls.js
With the new [fiddle.electronjs.org/launch](https://fiddle.electronjs.org/launch) page, validation takes place there - here the only thing left is to inject the current docs version.
ref https://github.com/electron/fiddle.electronjs.org/pull/1
cc @MarshallOfSound @zeke
=> fix: change url format of fiddle transformer

package-lock.json
Husky 4.0.9 broke the pre-push hook 😔
Reverts electron/i18n#1053
=> build: Revert "build(deps-dev): bump husky from 4.0.7 to 4.0.9"

.github/dependabot.yml
To limit the noise for notifications, this PR changes the dependency checks from daily to weekly. There are a lot of dev deps in this repo, and they're all low-ish priority to keep up to date.
=> build: make dependabot only run weekly

lib/parsers/docs-parser.ts, test.js, test/index.js
Had to rename some branches in Crowdin's side to get the flattening structure correctly.
This PR fixes the path again and should pass once the new sync is in place.
=> fix: path to get CrowdinFileId

lib/transfomers/remark-relative-links.ts, test/index.js
Fixes #1842 
Currently, the relative link fixer only checks for nodes of type `link`. This PR extends the fix to [`definition`](https://github.com/syntax-tree/mdast#definition) nodes so that relative links added with `remark-inline-links` work.
=> fix: run relative link transformer on `definition` nodes as well

lib/transfomers/remark-fiddle-urls.ts
The new electron docs website has support for optional parameters when embedding a fiddle. This PR just makes sure we ignore them.
See electron/electronjs.org-new/pull/36
Manually verified by adding a `|focus=main.js` to `quick-start.md`.
**Without this change**
**With this change**
cc: @erickzhao
=> feat: ignore extra fiddle embed params

script/collect.ts
There are some files in electronjs.org-new that are not part of the
markdown that need to be translated as well.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Rel: https://github.com/electron/electronjs.org-new/issues/64
=> build: add files from electronjs.org-new

test/index.js
=> test: update values for new Crowdin URLs
