readme.md
Explain how content moves in and out of this repo, and why Crowdin was chosen as the localization platform.
cc @alebourne
=> add more detail to readme

content/en/api/api-descriptions.yml, content/en/api/electron-api.json, content/en/docs/README.md, content/en/docs/glossary.md, content/en/docs/tutorial/desktop-environment-integration.md, content/en/docs/tutorial/notifications.md, content/en/docs/tutorial/quick-start.md, content/en/website/locale.yml, script/build.js
This fixes and issue where the build script was accidentally YAMLizing a yaml string.
=> Avoid double yaml

.travis.yml, content/en/api/api-descriptions.yml, package.json, script/build.js
=> shake API descriptions into a flat tree

readme.md
=> call it yaml

readme.md
=> update list of reviewed localization vendors

index.js
This a performance improvement, so the work of processing translated files will only be done at server startup, not every time it's requested.
=> pre-translate API object when module is loaded

PULL_REQUEST_TEMPLATE
Hopefully this will help misguided folks find their way.
A partial fix for #35
=> add pull request template

lib/locales.js, test/index.js
=> fix: name for Canadian locale

content/zh-CN/api/api-descriptions.yml, content/zh-CN/docs/development/atom-shell-vs-node-webkit.md, content/zh-CN/docs/development/build-instructions-linux.md, content/zh-CN/docs/development/build-instructions-osx.md, content/zh-CN/docs/development/build-instructions-windows.md, content/zh-CN/docs/development/build-system-overview.md, content/zh-CN/docs/development/chromium-development.md, content/zh-CN/docs/development/clang-format.md, content/zh-CN/docs/development/coding-style.md, content/zh-CN/docs/development/debug-instructions-windows.md, content/zh-CN/docs/development/debugging-instructions-macos.md, content/zh-CN/docs/development/releasing.md, content/zh-CN/docs/development/setting-up-symbol-server.md, content/zh-CN/docs/development/source-code-directory-structure.md, content/zh-CN/docs/development/v8-development.md
Reverts electron/electron-i18n#113
=> Revert "New api-descriptions translations for zh-CN"

readme.md
Adds some usage docs to the README.
=> add usage docs

script/build.js, test/index.js
=> fix title parsing

script/collect.js
The collect script had a bug so I took the liberty of refactoring it to use async functions. So much less code now!
Created https://github.com/electron/electron-i18n/issues/128 as a reminder to `s/neo/master/g` when the time is right.
=> Refactor collect script

lib/language-table.js, readme.md
=> Updated URLs to Crowdin

.gitignore
=> Update .gitignore to ignore `node_modules/`

contributing.md
I made a slight change in the word.
=> fix word contributing.md

content/en-US/docs/README.md, content/en-US/docs/development/releasing.md, content/en-US/docs/tutorial/about.md, content/en-US/docs/tutorial/electron-versioning.md, content/en-US/docs/tutorial/installation.md, package.json, test/index.js
Pulls in the changes from https://github.com/electron/electron/pull/11367
=> feat: update docs

package.json, script/i18n-content-cleanup.js, script/update-source-content.sh
- Adds a script that removes localized content that should have been deleted along with its English original
- Makes script part of `update-source-content` that runs as a scheduled task on Heroku
- Resolve #198 & unblock #222
=> Clean up removed files

script/build-module.js, test/index.js
Close #229 and related to https://github.com/electron/electronjs.org/pull/975
=> Crowdin file ID property

.github/PULL_REQUEST_TEMPLATE, .github/config.yml, package.json, readme.md, script/readme.js, script/update-source-content.sh
Resolves #255 
cc @vanessayuenn
=> shorten repo name to i18n

script/build-module.js, test/index.js
=> remove markdown and html from doc objects

test/index.js
=> fix: disable test that's blocking new docs from being pulled in

script/build-module.js
=> feat: unignore readme

contributing.md
- add limited proofreader section
- add some missing url link
=> fix: describe proofreader role

package-lock.json, package.json
=> fix: use new semantic-release release syntax

package.json
=> Revert "Update travis-deploy-once to the latest version 🚀"

package.json
So we can get the collect script working again!
=> fix: lock github at known working version

package-lock.json, package.json, script/collect.js
=> use @octokit/rest

package-lock.json, package.json
Resolves https://github.com/electron/electronjs.org/issues/1265
=> fix: update hubdown for emoji shortcode support

.github/main.workflow
=> build: install deps before running automerger

.github/main.workflow
=> build: last thing with action

package-lock.json, package.json, script/collect.ts
This PR changes collect script from js to ts and given some space for me on the next changes with this script.
=> refactor: move collect script to typescript

lib/apis.js, lib/get-slugs.js
=> build: remove unused files

package-lock.json, package.json
we do not use Travis, also run `npm audit fix`
=> build: remove travis-deploy-once

.github/workflows/schedule-update-source-content.yml
=> chore: remove dryrun_action from upload source content

script/collect.ts
This PR fixes the issue when the `supportedVersions` is updated in the `package.json` but we still have the cached version with the old `supportedVersions`. Now we have a variable that makes this array works as expected. The versions in `package.json` still are available but not in this file.
=> refactor: use in file constant instead of use package.json version

package-lock.json, package.json, script/collect.ts, script/get-cache.ts
=> build: update octokit to v18

contributing.md
=> docs: more details on adding/removing languages

package.json
=> chore: remove js-yaml dependency

.github/workflows/schedule-download-translations.yml, .github/workflows/schedule-update-source-content.yml
=> build: update crowdin github action to 1.1

readme.md
=> chore: make readme.md more readable

script/automerge.ts
Crowdin deletes now the branch once it is merged.
Waiting for @MarshallOfSound to confirm that he didn't deleted the `l10n_master` branch in the middle of the night.
=> build: automerge branch deletion

test/index.js
=> test: update values for new Crowdin URLs (again)
